### ISSUE TITLE
Add support for .tak audio

### ISSUE THREAD

**Issue by dubbz82** [john32b/cdcrush.net#9]
This is really a suggestion, not an issue, however it may be worth looking at TAK audio in addition to FLAC for lossless audio, as it allows for even better lossless compression than FLAC.  There's a CLI version of the compressor available, so parameters should be able to be passed in using a similar method as the other supported codecs are.  Here's some information about TAK if you're not familiar with it: https://wiki.hydrogenaud.io/index.php?title=TAK

**Comment by john32b** [comment]
I looked into this a bit. The TAK encoder only seems to be working with `.wav` files, where I need it to work with `pcm` files. *(raw audio data, as it is on the CDDA)*

FFmpeg works well , because it supports converting from and to PCM CD Audio out of the box, also ffmpeg does seem to have some TAK functionality but it only supports decoding from it, not encoding to the format. (which can't work, we need both encoding+decoding)

Perhaps there is a way to quickly convert a PCM->WAV so it can be passed to the TAK encoder. *I want to avoid copying PCM files to entirely new WAV files*, Perhaps there is a way of adding some header data at the beginning of the PCM files to convert them to WAV? And them from TAK->WAV I could just strip the headers and have raw PCM.

I'm leaving this open, I will come back to it!

**Comment by john32b** [comment]
Yeah, it works, I can do this with piping output from ffmpeg to takc. So a PCM can be converted to TAK on the fly. And the codec does seem to be fast and produce nicely compressed results. 

I'll implement this soon!

**Comment by dubbz82** [comment]
Nice!
